name: WarlordsBotManager
version: ${project.version}
main: com.ebicep.warlordsbotmanager.WarlordsBotManager
softdepend:
  - Warlords
commands:
  serverstatus:
    description: Toggle server status
    usage: /serverstatus
  discord:
    description: Link and unlink discord account with minecraft account
    usage: /discord
  queue:
    description: Queue system
    usage: /queue
  bot:
    description: Runs bot commands
    usage: /bot